import "./globals.css";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import Header from "./components/Header";
import { DarkThemeProvider } from "./utils/ThemeProvider";

const gro = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <DarkThemeProvider>
        <body
          className={`${gro.className} dark:bg-dark transition-all ease-in-out`}
        >
          <Header />
          {children}
        </body>
      </DarkThemeProvider>
    </html>
  );
}
